services:

  postgres:
    image: postgres:17
    container_name: changelens-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: changelens
      POSTGRES_USER: changelens
      POSTGRES_PASSWORD: changelens

    ports:
      - "5432:5432"

    volumes:
      - changelens-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U changelens -d changelens"]
      interval: 5s
      timeout: 5s
      retries: 10


  kafka:
    image: apache/kafka:4.0.0
    container_name: changelens-kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      # KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Internal Docker communication
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      # Host application communicates through localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_NUM_PARTITIONS: 3

    volumes:
      - changelens-kafka-data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10


  redis:
    image: redis:8-alpine
    container_name: changelens-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - changelens-redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


volumes:

  changelens-postgres-data:
    name: changelens-postgres-data

  changelens-kafka-data:
    name: changelens-kafka-data

  changelens-redis-data:
    name: changelens-redis-data