-- Audit Event Table
CREATE TABLE audit_event (
    event_id UUID PRIMARY KEY,
    event_version INTEGER NOT NULL,
    tenant_id VARCHAR(64),
    event_type VARCHAR(32) NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    action VARCHAR(128) NOT NULL,

    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(64),
    actor_name VARCHAR(128),

    resource_type VARCHAR(128),
    resource_id VARCHAR(128),
    resource_name VARCHAR(256),

    application_name VARCHAR(128) NOT NULL,
    application_version VARCHAR(64),
    service_name VARCHAR(128) NOT NULL,
    environment VARCHAR(32),

    request_id VARCHAR(64),
    correlation_id VARCHAR(64),
    trace_id VARCHAR(64),
    source_ip VARCHAR(64),
    user_agent VARCHAR(512),

    before_state JSONB,
    after_state JSONB,
    extensions JSONB,

    created_at TIMESTAMPTZ NOT NULL
);

-- Show the complete history of resource X
CREATE INDEX idx_audit_event_resource_timeline
    ON audit_event (
        tenant_id,
        resource_type,
        resource_id,
        event_timestamp DESC
    );

-- Show recent audit activity for a tenant
CREATE INDEX idx_audit_event_tenant_timestamp
    ON audit_event (
        tenant_id,
        event_timestamp DESC
    );

-- Show everything changed by this actor
CREATE INDEX idx_audit_event_actor_timeline
    ON audit_event (
        tenant_id,
        actor_id,
        event_timestamp DESC
    );

-- Audit Change Table
CREATE TABLE audit_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id UUID NOT NULL,

    field_path VARCHAR(512),
    field_name VARCHAR(64),
    display_name VARCHAR(512),

    change_type VARCHAR(32) NOT NULL,

    old_value JSONB,
    new_value JSONB,

    CONSTRAINT fk_audit_change_event
        FOREIGN KEY (event_id)
        REFERENCES audit_event(event_id)
);

CREATE INDEX idx_audit_change_event_id
    ON audit_change (event_id);

-- Audit Processing Table
CREATE TABLE audit_processing (
    event_id UUID PRIMARY KEY,

    status VARCHAR(32) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,

    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ,

    last_error VARCHAR(2048),

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_audit_processing_event
        FOREIGN KEY (event_id)
        REFERENCES audit_event(event_id),
    CONSTRAINT chk_audit_processing_attempts
            CHECK (attempts >= 0)
);

CREATE INDEX idx_audit_processing_status
    ON audit_processing (status, updated_at);

-- Audit DLQ Table
CREATE TABLE audit_dlq (
    event_id UUID PRIMARY KEY,

    status VARCHAR(32) NOT NULL,
    attempts INTEGER NOT NULL,

    payload JSONB NOT NULL,

    error_message VARCHAR(2048) NOT NULL,

    failed_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,

    CONSTRAINT fk_audit_dlq_event
        FOREIGN KEY (event_id)
        REFERENCES audit_event(event_id),
    CONSTRAINT chk_audit_dlq_attempts
        CHECK (attempts > 0)
);

CREATE INDEX idx_audit_dlq_status
    ON audit_dlq (status, failed_at DESC);

-- Outbox Event table
CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id UUID NOT NULL UNIQUE,

    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id VARCHAR(128),

    event_type VARCHAR(32) NOT NULL,

    payload JSONB NOT NULL,

    status VARCHAR(32) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,

    attempts INTEGER NOT NULL DEFAULT 0,

    last_error VARCHAR(2048),

    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_outbox_event_pending
    ON outbox_event (status, created_at);